// API layer: client, query keys, hooks, domain types (FE-02/03)
export * from './hooks'
export * from './types'
export { api, API_MODE } from './client'
export type { CaseFilter } from './surface'
export { caseOfItem } from './surface'
export { ProblemError } from './problem'
export { useConnection } from './connection'
export { keys } from './keys'
export { loadSlices } from './mock/slices'
export { queryClient } from './queryClient'
export { isViewPid, viewPath, viewPid } from './view'
